definitions:
  handler.ProductRequest:
    properties:
      code_value:
        type: string
      expiration:
        type: string
      is_published:
        type: boolean
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
    required:
    - code_value
    - expiration
    - name
    - price
    - quantity
    type: object
  web.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  web.SuccessfulResponse:
    properties:
      data: {}
    type: object
info:
  contact:
    email: ricardoivan.cruz@mercadolibre.com.mx
    name: Ricardo Cruz
    url: http://www.swagger.io/support
  description: This API simulates handling of MELI Products.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: MELI Bootcamp API
  version: "1.0"
paths:
  /products:
    get:
      consumes:
      - application/json
      description: Get All Products
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.SuccessfulResponse'
      summary: List Products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Create a Product
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Product
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.ProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.SuccessfulResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Create Product
      tags:
      - Products
swagger: "2.0"
